library(ChemmineR)
library(fmcsR)
library(dendextend)
library(RFLPtools)
library(viridis)
library(gplots)
library(MASS)
library(ggplot2)
library(bioassayR)
library(biomaRt)

source("CHEMIO.R")
source("CHEMAnalysis.R")
source("CHEMDisplay.R")
source("CHEMBioassay.R")


listCHEMMethods <- function() {
  print("CHEMIO.R")
  print("importSDFFromCID(CIDvector) : returns SDFset")
  print("loadCHEMDF(fileName) : returns data.frame")
  print("loadCIDFile(fileName) : returns data.frame (drugName, CID)")
  print("loadSDFFile(fieName) : returns SDFset")
  print("loadClusterMatrix(fileName) : returns matrix")
  print("saveCHEMDF(df,fileName)")
  print("saveClusterMatrix(simMatrix, fileName)")
  print("saveSDFFile(SDFset, fileName)")
  print("=======================================")

  print("CHEMAnalysis.R")
  print("calculateFMCS(sdfObject1, sdfObject2, au=2, bu=1) : returns an fmcs object")
  print("calculateNumAtomsToMCSReference(referenceSDF, ignoreIndex, SDFset, drugNameVector, au=2, bu=1) : returns data.frame for plotting")
  print("clusterWithFMCSAromatic(SDFset, au=2, bu=1, overlapCoefficient=TRUE) : returns a matrix of similarities")
  print("clusterWithFMCSStatic(SDFset, au=2, bu=1, overlapCoefficient=TRUE) : returns a matrix of similarities")
  print("clusterWithFMCSRing(SDFset, au=2, bu=1, overlapCoefficient=TRUE) : returns a matrix of similarities")
  print("=======================================")

  print("CHEMDisplay.R")
  print("displayClusterDend(simMatrix) : returns dendrogram objecct for plot()")
  print("displayClusterHeatMap(simMatrix, CIDvector, title=NULL) : returns heatmap object for plot()")
  print("displayFMCSSize(df, fileNameJPEG) : returns ggplot object")
  print("getNCBIFractionActivity(drugTargetsMat, title=NULL) : returns ggplot object")
  print("=======================================")

  print("CHEMBioassay.R")
  print("getBioassayDatabase(DBLocation) : returns a db object, don't forget to close it")
  print("getEnsemblProteinDetails(uniProtIDs, attributeCharVector, filtersCharVector, drugTargets) : returns list of protein details")
  print("getProteinDrugTargets(db, CID) : returns a dataframe (within a list) showing the drug targets (protein), the number of total assay screens and the total fraction of activity")
  print("getUniProtIDs(NCBIMatrix, db) : returns a list of uniprot IDs")
  print("clusterCompoundsByActivityProfile(db, compoundCIDs) : returns hcluster object")
}
